README.md, main.go, nuv_test.go, tests/awk.bats, tests/testdata/awk_test.txt
This PR adds some awk.bats tests
=> Add awk bats tests

go.sum, main.go, serve.go, serve_test.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/163
It adds the endpoint /api/nuv to run tasks
=> Add /api/nuv to run tasks

auth/login.go, auth/login_test.go, auth/password_reader.go, auth/password_reader_test.go, go.mod, go.sum, main.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/104
It adds the `nuv -login` command that asks for a password and sends a post request to the login web action. The credentials retrieved are then stored to the os secrets using zalando/go-keyring.
=> Login command

bin/nuvfile.yml, bin/windows/wix.json
added download of MINIO mc client
=> feature: added download of MINIO mc client

main.go, prepare.go, prepare_test.go, tests/update.bats
This PR closes https://github.com/nuvolaris/nuvolaris/issues/175
It moves the prints to the user in downloadTasksFromGitHub so it can print different things depending on the update result.
=> Fix -update feedback

common.go, config.go, config_test.go, go.mod, main.go, nuv.go, prepare.go, tests/config.bats, tools/tools.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/184
It reads config.json and nuvroot.json to load env vars when running nuv and adds the -config cmd to create config.json.
=> Add -config to create config.json

config.go, config_test.go, tests/config.bats, tests/datefmt.bats, tools/datefmt.go, tools/tools.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/178
It adds the -datefmt tool
=> Add Datefmt tool

auth/login.go
Implements the set apihost and auth after login described in https://github.com/nuvolaris/nuvolaris/issues/191
=> fix error handling and set properties

.github/workflows/check.yml, tests/config.bats, tests/datefmt.bats, tests/js.bats
This PR adds another job to run the bats tests in the tests folder
=> Add CI action for bats tests

.github/workflows/check.yml, auth/login_test.go, common.go, config_test.go, main_test.go, nuv.go, nuv_test.go, prepare.go, prepare_test.go, serve.go, serve_test.go, updates_check.go, updates_check_test.go
This PR adds a lint check in the check action and fixes all the warnings (error handling missing, deprecated functions etc)
=> Add lint check CI job 

config.go, config_test.go, go.sum, tests/config.bats
close https://github.com/nuvolaris/nuvolaris/issues/195
It adds nuv config --remove (-r) that takes in a list of strings.
=> add --remove to config tool

go.mod, go.sum, tests/find.bats, tools/find.go, tools/tools.go
Implement find tool as defined in https://github.com/nuvolaris/nuvolaris/issues/198
=> add -find tool

tests/validate.bats, tools/tools.go, tools/validate.go, tools/validate_test.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/209
It adds the -validate tool
=> Implement https://github.com/nuvolaris/nuvolaris/issues/209

go.mod, go.sum, tools/js.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/199
=> update js tool

prepare.go, tests/olaris/update/nuvfile.yml, tests/update.bats
This PR closes https://github.com/nuvolaris/nuvolaris/issues/215
=> add auto update with nuv update cli

go.mod, go.sum, nuv.go, nuv_test.go, tests/olaris/sub/opts/nuvopts.txt, tests/opts.bats
Close https://github.com/nuvolaris/nuvolaris/issues/216
=> apply envsubst on nuvopts usage

tests/echoif.bats, tools/echo.go, tools/tools.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/226
it adds the echoif, echoifempty and echoifexists tools
=> Implement https://github.com/nuvolaris/nuvolaris/issues/226

config/config_map.go, config/config_map_builder.go, config/config_map_builder_test.go, config/config_tool.go, config/config_tool_test.go, main.go, plugin.go, plugin_test.go, tests/olaris-plugin/nuvroot.json, tests/olaris/nuvroot.json, tests/plugin.bats
Close https://github.com/nuvolaris/nuvolaris/issues/244
This PR adds the possibility to add a config to the nuvroot.json files in the plugins that gets picked up by nuv and added to the complete config map. The config keys from a plugin are all prefixed with the name of the plugin.
=> Plugin configs

main.go, nuv.go, plugin.go, plugin_test.go
The print help message for plugins was not updated with the correct local folder
=> fix: get local folder from NUV_PWD in plugins

main.go, nuv.go, tests/plugin.bats, tests/testdata/olaris-other/nuvfile.yml, tests/testdata/olaris-other/nuvroot.json, tests/testdata/olaris-other/sub/nuvfile.yml, tests/update.bats, tools/echo.go
This PR fixes the problem when using nuv commands from a plugin
=> remove NUV_ROOT overwrite

tools/realpath.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/257
=> Expand ~ in realpath

go.mod, go.sum, tests/js.bats, tools/js.go
This PR updates to the latest goja_nodejs dep that adds the nuv module
=> Update nuv deps

prepare.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/283
=> feat: add branch checkout during update

README.md, main.go, tests/scan.bats, tools/tools.go
Close https://github.com/nuvolaris/nuvolaris/issues/292
=> Remove old tools and disable nuv_pwd override

main.go, prepare.go, prepare_test.go, tests/auto_setup.bats, tests/update_branch.bats, updates_check.go, updates_check_test.go
This PR fixes the `nuv -update` called with a different branch set. Possible fix for https://github.com/nuvolaris/nuvolaris/issues/291 and https://github.com/nuvolaris/nuvolaris/issues/289
=> Fix git pull on nuv branch

tests/validate.bats, tools/validate.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/290
=> refactor: validate tool

prepare.go, tests/needupdate.bats, tools/needupdate.go, tools/random.go, tools/random_test.go, tools/tools.go
Close https://github.com/nuvolaris/nuvolaris/issues/306
This PR adds the `nuv -needupdate` tool that can check if a semver string is greater then another. It also updates the random tool code by using its own FlagSet and adds an update to the latestcheck file when calling `nuv -update` manually.
=> Add needupdate tool

bin/nuvfile.yml
This PR adds the coreutils binary with the installation of nuv
=> feat: add coreutils binary

serve.go, serve_test.go, tools/deploy.go, tools/deploy_test.go, tools/tools.go
This PR adds -serve tool which opens a webserver on the input directory.
=> Add back -serve

main.go, main_test.go
This PR closes https://github.com/nuvolaris/projects/issues/125
=> Enable k=v notation for invoke parameters
