nuvolaris/nuv

- go.mod
- go.sum
- tools/tools.go
This PR closes #1
It adds the github.com/nuvolaris/goawk dependency in go.mod with latest commit. I've also run `go mod tidy` to clean go.mod. 
The tool is added to the switch case in tools.go with a small refactor to the IsTool function, I've made an array of string for the check like it works in IsUtils so it will be easier to add more tools later.
> Embed goawk tool

- go.mod
- go.sum
- tools/tools.go
This PR closes #5 
It adds the envsubst tool from the github.com/nuvolaris/envsubst/cmd/envsubstmain repo, and it can be used as `nuv -envsubst`
> Add envsubst tool

- main.go
- nuv.go
- nuv_test.go
- tests/opts.bats
- tests/prefixes.bats
- tools/tools.go
This PR closes #9 
It adds a validateTaskName function that is used when running a task. It reads the nuvfile.yml in the current directory to grab the list of task names and performs some validation to check that the input arg task is present in the list of if it is a prefix. In case it's a prefix the input arg task is swapped with the proper name. in case of ambiguity it returns an error.
> Add prefix usage to run tasks

- main.go
- tests/js.bats
- tests/testdata/js_function_test.js
- tests/testdata/js_simple_test.js
- tools/js.go
- tools/tools.go
Wrap the goja tool into tools/js.go to add the `-h` flag and check if no input is given. 
The PR also adds some bats tests in `tests/js.bats` for the js tool. 
The PR is built starting from the commits in #16 so that should be merged before (it uses the no log prefix variable).
> Refactor js tool

- README.md
- common.go
- main.go
- prepare.go
- tests/update.bats
This PR closes #12 and it is based on #16 
It adds version validation when updating tasks with `nuv -update`. After downloading the tasks from github the `nuvroot.json` file is parsed and the version field is compared to the NuvVersion var using the semver package. In case of a version older than the one in nuvroot, a warning is printed to inform the user.
> Version checking when updating

- tools/filetype.go
- tools/js.go
- tools/mkdirs.go
This PR fixes #20 
In mkdir, filetype and js tools the usage print is done with flag.Usage() which fixes the bugged usage print when passing a wrong flag.
> Fix usage print when given unknown flag

- go.mod
- go.sum
- main.go
- nuv.go
- task.go
- tests/opts.bats
This PR closes #13
The updated taskmain returns an exitCode, error so they are now used to catch and log Task errors.
> Update taskmain use with errors

- README.md
- common.go
- go.mod
- go.sum
- main.go
- prepare.go
- serve.go
- serve_test.go
- tests/olaris/web/index.html
- tools/tools.go
This PR adds the '-serve' command to start a http.FileServer on the olaris/web folder. It also adds the browser package to start the server and open the browser on http://localhost:9678. The default port is 9678 but it can be changed with NUV_PORT env var.
closes https://github.com/nuvolaris/nuvolaris/issues/159
> Add web server on olaris/web folder

- .github/workflows/check.yml
- README.md
This PR updates the check action by separating the license check and go test in 2 jobs that are also run on PRs and adds some badges in the README.
> Refactor action and add shields in README

- nuv.go
- nuv_test.go
- tests/folders.bats
- tests/olaris/other/nuvfile.yml
This PR closes https://github.com/nuvolaris/nuvolaris/issues/165 
It now also picks up subfolders with a nuvfile.yml inside as tasks that are not in the root nuvfile.yml
> Consider subfolders with nuvfile as candidates

- main.go
- prepare.go
- updates_check.go
- updates_check_test.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/182
It moves the creation of the .latestcheck file only when downloading tasks from github the first time in the ~/nuv folder.
> create check file only in home dir

- tests/random.bats
- tools/random.go
- tools/random_test.go
- tools/retry.go
- tools/tools.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/177
It adds the `nuv -random` tool that can be used to generate floats, ints in ranges, strings and uuids.
The flags are:
-  `-u` or `--uuid` for uuids v4.
- `--int` to generate integers
- `--str` to generate strings
- no flags to generate a float between 0-1
> Add -random tool

- config.go
- config_test.go
- tests/config.bats
- tools/tools.go
This PR fixes the bug indicated in https://github.com/nuvolaris/nuvolaris/issues/189
Now when multiple keys that define maps are set, they don't overwrite each other but are merged
> Merge config keys maps

- config.go
- config_test.go
- tests/config.bats
This PR closes https://github.com/nuvolaris/nuvolaris/issues/189
It adds a flag to the config tool `--dump` and shorthand `-d` to print all env vars in nuvroot.json and config.json
> Add --dump flag to config tool

- auth/login.go
- auth/login_test.go
- main.go
Small fix when calling `nuv -login` with no args
> fix login tool nil error

- config.go
- config_test.go
- tests/config.bats
This PR closes https://github.com/nuvolaris/nuvolaris/issues/203
The `nuv -config` tool can now read the values of keys in config.json by passing keys (without "=")
> implement https://github.com/nuvolaris/nuvolaris/issues/203

- main.go
- tests/folders.bats
- tests/olaris-test/nuvfile.yml
Small fix when a task is not found in olaris nor in plugins the wrong error was returned
> Return correct task not found error

- plugin.go
- tests/plugin.bats
This PR implements the plugin update by running `nuv -plugin <repo>` with an existing plugin repo
> update plugin repo when already existing

- auth/login.go
- auth/login_test.go
- config/config_map.go
- config/config_map_test.go
- config/config_tool.go
- config/config_tool_test.go
This PR refactors the login command to store the returned secrets in the nuv config instead of the keyring store as a temporary solution, as the keyring store has some cases where it can't be used (when not present)
https://github.com/nuvolaris/nuvolaris/issues/224
> Login add user secrets to config

- main.go
- tests/realpath.bats
- tools/realpath.go
- tools/tools.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/225
It adds the `nuv -realpath` tool that when a relative is passed, it prints $NUV_PWD/path where NUV_PWD is the directory where nuv was used. If it's an absolute path, it just prints it.
Also the PR adds a fix for the place where NUV_TMP is set so it appears in nuv -info
> Implements https://github.com/nuvolaris/nuvolaris/issues/225

- main.go
- preflight.go
- preflight_test.go
This PR closes https://github.com/nuvolaris/nuvolaris/issues/239
It adds 2 preflight checks that are run when nuv is launched and it checks that curl and ssh are available in PATH
> Add checks for curl and ssh

- main.go
This PR fixes a bug where NUV_PWD was being overridden every time and -realpath tool was not working properly as a result.
> fix: don't override NUV_PWD if already set

- main.go
- tests/wsk_wrapper.bats
Closes https://github.com/nuvolaris/nuvolaris/issues/253
Add a check that the input command is a wsk wrapper (action, activation, invoke, etc) and run tools.Wsk instead of running task commands.
> Add wsk wrapper commands

- tests/zipf.bats
- tools/tools.go
- tools/zipf.go
- tools/zipf_test.go
Close https://github.com/nuvolaris/nuvolaris/issues/266
This PR adds the `nuv -zipf` tool. It zips a folder with the proper name based on the action contained.
> Add -zipf tool

- plugin.go
This PR closes https://github.com/nuvolaris/nuvolaris-bugs/issues/10
it adds a check in the plugin detection to be sure the plugin is a folder
> Fix https://github.com/nuvolaris/nuvolaris-bugs/issues/10

- main.go
Close https://github.com/nuvolaris/nuvolaris/issues/271
This PR adds a check at the start of the main for the ~/.nuv folder. If it's not found it execute the -update code
> Add first time auto update

- go.mod
- go.sum
- tools/zipf.go
This PR updates the deps for the updated goja_nodejs nuv module to be used for the deployer in olaris.
> Update goja_nodes and zipf

- README.md
- main.go
- main_test.go
- plugin.go
- plugin_test.go
Close https://github.com/nuvolaris/nuvolaris/issues/297
This PR adds another env var NUV_ROOT_PLUGIN to customize the plugin folder root and separate it from NUV_PWD
> Add NUV_ROOT_PLUGIN to be used for plugins

- prepare.go
- tools/needupdate.go
This PR adds the check on the operator tag in olaris. If in olaris there is a newer version a message is printed to the user advising to run `nuv update operator`
It completes https://github.com/nuvolaris/nuvolaris/issues/303
> feat: add operator version check

- README.md
- go.mod
- go.sum
- main.go
- prepare.go
- prepare_test.go
- tests/info.bats
Close https://github.com/nuvolaris/nuvolaris/issues/296
This PR adds the env var NUV_OLARIS which holds the head hash commit of the used olaris repo. It is visible via `nuv -info`.
> add NUV_OLARIS 

- README.md
- auth/login.go
- tests/login.bats
This PR closes https://github.com/nuvolaris/nuvolaris/issues/338 
It updates nuv -login with 3 env vars: "NUV_APIHOST", "NUV_USER" and "NUV_PASSWORD".
With NUV_APIHOST, you set the apihost and the first argument of nuv -login becomes the user. 
With NUV_USER you set the user and override any user argument.
With NUV_PASSWORD you set the password for the login and skip the interactive prompt.
> Update nuv -login with NUV_APIHOST

- main.go
This PR moves the application of the env vars from the config above the execution of tools and special tasks so the env vars are available in the tools
> refactor: move config env var above tool exec

- nix/default.nix
- nix/nuv.nix
- nix/result
This show how to start a shell with a shell.nix including a derivation that is not yet on nixpkgs. Resolves [nuvolaris#175](https://github.com/nuvolaris/projects/issues/175)
> feat: shell with a derivation not yet on nixpkgs
